# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  mailer:
    username: <%= ENV['MAILER_USERNAME'] %>
    password: <%= ENV['MAILER_PASSWORD'] %>

development:
  <<: *default
  secret_key_base: c6eb5e3f46b3c40b170914a28f6c31970783bd518696ffb49bc0ca3029b4c0b4cf4efb5c4b11327afebdaadb5c910ea3d48346ba198098610882bb002419eb4a

test:
  <<: *default
  secret_key_base: 9e027991cb29ffb0368f81a68fa59e5a0602ee80bbe7147572a641b0abca5acd3229e69e08d3586c4908040139cdb46cfa98ac2f88d9236cae835cc6784b7766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
